const express = require('express')
const { twig } = require('twig')

const app = express()

app.set('view engine', 'twig')


const homeController = require('./controllers/home.controller')
const solarSystemController = require('./controllers/solarSystem.controller')
const starsController = require('./controllers/stars.controller')
const mysolarController = require('./controllers/mysolar.controller')
const zodiacController = require('./controllers/zodiac.controller')
const stargroupController = require('./controllers/stargroup.controller')
const starlController = require('./controllers/starl.controller')
const loadController = require('./controllers/load.controller')
const helpController = require('./controllers/help.controller')
const inforController = require('./controllers/infor.controller')
const smallbController = require('./controllers/smallb.controller')
const bigbController = require('./controllers/bigb.controller')
const batController = require('./controllers/bat.controller')
const naipController = require('./controllers/naip.controller')
const nucketController = require('./controllers/nucket.controller')
const picaController = require('./controllers/pica.controller')

const short_sunController = require('./controllers/solars_controller/short_sun.controller')
const short_mercuryController = require('./controllers/solars_controller/short_mercury.controller')
const short_venusController = require('./controllers/solars_controller/short_venus.controller')
const short_earthController = require('./controllers/solars_controller/short_earth.controller')
const short_marsController = require('./controllers/solars_controller/short_mars.controller')
const short_jupiterController = require('./controllers/solars_controller/short_jupiter.controller')
const short_saturnController = require('./controllers/solars_controller/short_saturn.controller')
const short_uranusController = require('./controllers/solars_controller/short_uranus.controller')
const short_neptuneController = require('./controllers/solars_controller/short_neptune.controller')

const full_sunController = require('./controllers/solars_controller/full_sun.controller')
const full_mercuryController = require('./controllers/solars_controller/full_mercury.controller')
const full_venusController = require('./controllers/solars_controller/full_venus.controller')
const full_earthController = require('./controllers/solars_controller/full_earth.controller')
const full_marsController = require('./controllers/solars_controller/full_mars.controller')
const full_jupiterController = require('./controllers/solars_controller/full_jupiter.controller')
const full_saturnController = require('./controllers/solars_controller/full_saturn.controller')
const full_uranusController = require('./controllers/solars_controller/full_uranus.controller')
const full_neptuneController = require('./controllers/solars_controller/full_neptune.controller')

app.get('/home', homeController.index)
app.get('/our-solar-system', solarSystemController.index)
app.get('/our-star', starsController.index)
app.get('/our-mysolar', mysolarController.index)
app.get('/our-zodiac',zodiacController.index)
app.get('/our-stargroup',stargroupController.index)
app.get('/our-starline',starlController.index)
app.get('/',loadController.index)
app.get('/help',helpController.index)
app.get('/information',inforController.index)
app.get('/smallbear',smallbController.index)
app.get('/bigbear',bigbController.index)
app.get('/bat',batController.index)
app.get('/nai-pran',naipController.index)
app.get('/Look-kai',nucketController.index)
app.get('/Pigasus',picaController.index)

app.get('/our-solar-system/short_sun',short_sunController.index)
app.get('/our-solar-system/short_mercury',short_mercuryController.index)
app.get('/our-solar-system/short_venus',short_venusController.index)
app.get('/our-solar-system/short_earth',short_earthController.index)
app.get('/our-solar-system/short_mars',short_marsController.index)
app.get('/our-solar-system/short_jupiter',short_jupiterController.index)
app.get('/our-solar-system/short_saturn',short_saturnController.index)
app.get('/our-solar-system/short_uranus',short_uranusController.index)
app.get('/our-solar-system/short_neptune',short_neptuneController.index)

app.get('/our-solar-system/full_sun',full_sunController.index)
app.get('/our-solar-system/full_mercury',full_mercuryController.index)
app.get('/our-solar-system/full_venus',full_venusController.index)
app.get('/our-solar-system/full_earth',full_earthController.index)
app.get('/our-solar-system/full_mars',full_marsController.index)
app.get('/our-solar-system/full_jupiter',full_jupiterController.index)
app.get('/our-solar-system/full_saturn',full_saturnController.index)
app.get('/our-solar-system/full_uranus',full_uranusController.index)
app.get('/our-solar-system/full_neptune',full_neptuneController.index)

app.use('/assets', express.static(__dirname + '/static/assets', { maxAge: 86400000 }))
app.use('/images', express.static(__dirname + '/static/images', { maxAge: 86400000 }))

app.use('/archive', express.static(__dirname + '/archive', { maxAge: 0 }))

module.exports = app
